#!/usr/bin/env  bash

# Get the full path to the script file
script_path="${BASH_SOURCE[0]}"

# Resolve symlinks (if any)
while [ -h "$script_path" ]; do

  # Find the directory of the script path
  script_dir="$(cd -P "$(dirname "$script_path")" && pwd)"

  # Read the symlink to find out where it points
  script_path="$(readlink "$script_path")"

  # Handle relative symlinks
  [[ $script_path != /* ]] && script_path="$script_dir/$script_path"
done
script_dir="$(cd -P "$(dirname "$script_path")" && pwd)"


echo "$@" >>"$script_dir/tmp/log.txt"
